name: test

on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout upstream repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-go@v2
        with:
          go-version: "1.18"

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: go test ./test

  vet:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: go vet ./...
